# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_follower}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{uthor Name}]
  s.date = %q{2011-07-18}
  s.description = %q{longer description of your gem}
  s.email = %q{email@address.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "acts_as_follower.gemspec",
    "lib/acts_as_follower.rb",
    "lib/acts_as_follower/followable.rb",
    "lib/acts_as_follower/follower.rb",
    "lib/acts_as_follower/follower_lib.rb",
    "lib/generators/USAGE",
    "lib/generators/acts_as_follower_generator.rb",
    "lib/generators/templates/migration.rb",
    "lib/generators/templates/model.rb",
    "test/TESTING",
    "test/acts_as_followable_test.rb",
    "test/acts_as_follower_test.rb",
    "test/database.yml.example",
    "test/factories/bands.rb",
    "test/factories/users.rb",
    "test/follow_test.rb",
    "test/models/band.rb",
    "test/models/user.rb",
    "test/schema.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{https://github.com/sid137/acts_as_follower}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/acts_as_followable_test.rb",
    "test/acts_as_follower_test.rb",
    "test/factories/bands.rb",
    "test/factories/users.rb",
    "test/follow_test.rb",
    "test/models/band.rb",
    "test/models/user.rb",
    "test/schema.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

